The problem here is to predict the sales of the store. 'Item_Outlet_Sales' variable is the dependent variable & the rest others are independent variables.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [2]:
data = pd.read_csv('C:/Users/Chinmay Gupta/Desktop/Data set/Linear Regression/train.csv')
data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [3]:
data = pd.get_dummies(data)

In [4]:
data.shape

(8523, 1605)

As the dataset has 8523 rows, we use 8000 rows as train dataset & 523 rows as test dataset.

In [5]:
# Making the train data set
train = data.iloc[0:7999]
train

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales,Item_Identifier_DRA12,Item_Identifier_DRA24,Item_Identifier_DRA59,Item_Identifier_DRB01,Item_Identifier_DRB13,...,Outlet_Size_High,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 1,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Grocery Store,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
0,9.300,0.016047,249.8092,1999,3735.1380,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
1,5.920,0.019278,48.2692,2009,443.4228,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
2,17.500,0.016760,141.6180,1999,2097.2700,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
3,19.200,0.000000,182.0950,1998,732.3800,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
4,8.930,0.000000,53.8614,1987,994.7052,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0
5,10.395,0.000000,51.4008,2009,556.6088,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
6,13.650,0.012741,57.6588,1987,343.5528,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0
7,NaN,0.127470,107.7622,1985,4022.7636,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,1
8,16.200,0.016687,96.9726,2002,1076.5986,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
9,19.200,0.094450,187.8214,2007,4710.5350,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
10,11.800,0.000000,45.5402,1999,1516.0266,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
11,18.500,0.045464,144.1102,1997,2187.1530,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0
12,15.100,0.100014,145.4786,1999,1589.2646,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
13,17.600,0.047257,119.6782,1997,2145.2076,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0
14,16.350,0.068024,196.4426,1987,1977.4260,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0
15,9.000,0.069089,56.3614,1997,1547.3192,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0
16,11.800,0.008596,115.3492,2009,1621.8888,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
17,9.000,0.069196,54.3614,1999,718.3982,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
18,NaN,0.034238,113.2834,1985,2303.6680,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,1
19,13.350,0.102492,230.5352,2004,2748.4224,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
20,18.850,0.138190,250.8724,1987,3775.0860,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0
21,NaN,0.035400,144.5444,1985,4064.0432,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,1
22,14.600,0.025698,196.5084,2004,1587.2672,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
23,NaN,0.057557,107.6938,1985,214.3876,0,0,0,0,0,...,0,0,1,1,0,0,1,0,0,0
24,13.850,0.025896,165.0210,1997,4078.0250,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0
25,13.000,0.099887,45.9060,2007,838.9080,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
26,7.645,0.066693,42.3112,2004,1065.2800,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
27,11.650,0.019356,39.1164,1987,308.9312,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0
28,5.925,0.161467,45.5086,1998,178.4344,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
29,NaN,0.072222,43.6454,1985,125.8362,0,0,0,0,0,...,0,0,1,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7969,11.650,0.032425,38.8164,1998,77.2328,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
7970,NaN,0.052301,88.2830,1985,2157.1920,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,1
7971,14.300,0.026363,78.3302,1999,1267.6832,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
7972,NaN,0.000000,45.7428,1985,615.1992,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,1
7973,8.355,0.187559,148.0418,1997,1471.4180,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0
7974,13.150,0.043764,183.0950,1997,1830.9500,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0
7975,19.250,0.000000,82.5908,2002,922.7988,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
7976,5.035,0.080073,228.2036,2002,2504.7396,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
7977,15.850,0.007146,41.0480,1997,798.9600,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0
7978,15.350,0.096318,197.3768,1987,3350.3056,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0
7979,12.500,0.020730,197.2742,1999,3782.4098,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
7980,18.350,0.157834,87.5882,1998,171.7764,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
7981,NaN,0.010929,167.0842,1985,6465.5838,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,1
7982,20.500,0.036110,120.1756,1987,2059.9852,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0
7983,13.850,0.030843,143.1154,1999,2552.6772,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
7984,4.590,0.000000,111.1860,2002,1245.0460,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
7985,10.000,0.089078,147.1102,1987,2916.2040,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0
7986,12.350,0.100164,113.6518,2009,1593.9252,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
7987,NaN,0.045764,43.8744,1985,1222.4088,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,1
7988,20.000,0.103997,107.4622,1987,1587.9330,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0
7989,13.800,0.057104,232.6984,2009,1390.1904,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
7990,9.500,0.041971,33.3900,2002,732.3800,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
7991,5.425,0.114472,88.3514,1997,2833.6448,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0
7992,16.750,0.045117,187.9556,1999,2440.8228,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
7993,19.200,0.000000,223.8062,2002,5642.6550,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
7994,10.500,0.027276,171.3106,1997,3593.3226,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0
7995,12.850,0.152748,252.0382,2009,4037.4112,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
7996,NaN,0.060707,127.5020,1985,379.5060,0,0,0,0,0,...,0,0,1,1,0,0,1,0,0,0
7997,6.360,0.120788,45.7060,2002,838.9080,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
7998,NaN,0.076852,111.8570,1985,109.8570,0,0,0,0,0,...,0,0,1,1,0,0,1,0,0,0

In [6]:
# Making the test data set
test = data[8000:]
test

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales,Item_Identifier_DRA12,Item_Identifier_DRA24,Item_Identifier_DRA59,Item_Identifier_DRB01,Item_Identifier_DRB13,...,Outlet_Size_High,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 1,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Grocery Store,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
8000,7.020,0.081329,150.0734,2002,4454.2020,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
8001,7.420,0.020388,247.1092,2004,4233.1564,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
8002,17.250,0.113518,253.5724,1997,5033.4480,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0
8003,18.750,0.052917,190.6504,2002,1342.2528,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
8004,20.250,0.018911,220.5772,2007,2446.1492,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
8005,12.650,0.075981,192.3846,1987,1910.8460,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0
8006,12.500,0.018849,96.7384,1997,2167.8448,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0
8007,12.800,0.116528,261.4252,1998,262.3252,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
8008,6.655,0.000000,212.4586,2007,2743.7618,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
8009,10.300,0.070040,263.0226,1997,4229.1616,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0
8010,14.600,0.059827,239.2538,2007,3605.3070,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
8011,9.195,0.051827,77.4644,2009,1414.1592,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
8012,13.650,0.035954,185.2924,2004,3146.5708,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
8013,7.935,0.017183,51.2350,1999,848.8950,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
8014,20.750,0.007547,104.1622,1987,1693.7952,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0
8015,15.100,0.105831,41.6796,1999,784.3124,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
8016,NaN,0.018276,115.2808,1985,117.1808,0,0,0,0,0,...,0,0,1,1,0,0,1,0,0,0
8017,10.100,0.027064,76.3670,1997,765.6700,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0
8018,NaN,0.000000,100.3674,1985,1833.6132,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,1
8019,16.750,0.060640,173.0106,1999,3593.3226,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
8020,9.130,0.051847,152.8024,1997,1214.4192,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0
8021,8.235,0.014519,182.1950,2009,2380.2350,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
8022,16.850,0.159723,194.1478,1987,5812.4340,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0
8023,NaN,0.059117,181.5976,1985,4165.2448,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,1
8024,17.350,0.020556,79.4618,2004,1772.3596,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
8025,NaN,0.171384,50.5324,1985,207.7296,0,0,0,0,0,...,0,0,1,1,0,0,1,0,0,0
8026,14.500,0.090286,159.9604,2007,2218.4456,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
8027,14.500,0.061987,153.0998,1997,4921.5936,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0
8028,9.395,0.160236,227.8720,2007,1584.6040,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
8029,7.905,0.010033,248.3408,2002,751.0224,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8493,7.420,0.025886,189.1872,2007,4727.1800,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
8494,15.200,0.000000,110.4912,2007,1637.8680,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
8495,9.695,0.029567,160.4920,2004,4314.3840,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
8496,7.420,0.021696,185.3582,2007,3715.1640,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
8497,13.650,0.049209,150.0050,2004,2247.0750,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
8498,15.350,0.035293,124.5730,2009,1601.2490,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
8499,11.600,0.037574,100.0042,2004,2976.1260,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
8500,20.350,0.000000,125.1678,2007,1907.5170,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
8501,5.340,0.005998,100.4358,2007,1508.0370,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
8502,8.420,0.070712,216.4192,2002,3020.0688,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
8503,20.500,0.036133,120.1756,2004,3392.9168,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
8504,NaN,0.124111,111.7544,1985,4138.6128,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,1
8505,10.500,0.094146,210.8244,2009,2117.2440,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
8506,17.250,0.084676,263.1910,2009,3944.8650,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
8507,5.880,0.030242,101.7990,2004,515.9950,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
8508,11.350,0.043246,199.4742,2002,2587.9646,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
8509,8.100,0.214306,213.9902,1998,424.7804,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
8510,13.800,0.056862,231.5984,2004,7182.6504,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
8511,17.500,0.026980,262.5910,2009,4207.8560,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
8512,20.700,0.042801,178.3028,1987,2479.4392,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0
8513,12.000,0.020407,99.9042,2004,595.2252,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
8514,15.000,0.054489,57.5904,2002,468.7232,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
8515,20.700,0.021518,157.5288,2009,1571.2880,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
8516,18.600,0.118661,58.7588,2009,858.8820,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
8517,20.750,0.083607,178.8318,1997,3608.6360,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0
8518,6.865,0.056783,214.5218,1987,2778.3834,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0
8519,8.380,0.046982,108.1570,2002,549.2850,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
8520,10.600,0.035186,85.1224,2004,1193.1136,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
8521,7.210,0.145221,103.1332,2009,1845.5976,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
8522,14.800,0.044878,75.4670,1997,765.6700,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0

In [7]:
# For using the scikit learn algo, dropping the target variable from the column we use axis=1 & making this only independent one
x_train = train.drop('Item_Outlet_Sales',axis=1)
#x_train

In [8]:
# For using the scikit learn algo keeping the target variable at this place only
y_train = train[['Item_Outlet_Sales']]
#y_train

In [9]:
# The test data should not contain dependent variable, so dropping the dependent variable
x_test = test.drop('Item_Outlet_Sales',axis=1)
#x_test

In [10]:
# Keeping separately the target variable of the test dataset so to check it at last 
true_p = test['Item_Outlet_Sales']

In [11]:
from sklearn.linear_model import LinearRegression
# Creating an object lreg 
lreg = LinearRegression()

As Scikit cannot take string variables string values we will create dummies. No need to dummification as it has been done before in the 3rd one.

In [12]:
#x_train = pd.get_dummies(x_train)

In [13]:
x_train.shape

(7999, 1604)

In [14]:
#x_test = pd.get_dummies(x_test)

In [15]:
x_train.fillna(0,inplace=True)

In [16]:
x_test.fillna(0,inplace=True)

In [17]:
# Linear Regression has a function fit which fits the training data to the model
lreg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [18]:
pred= lreg.predict(x_test) 
pred

array([[ 2.41050e+03],
       [ 3.88550e+03],
       [ 3.84825e+03],
       [ 2.06900e+03],
       [ 4.75825e+03],
       [ 2.99300e+03],
       [ 1.88000e+03],
       [ 2.50875e+03],
       [ 3.52300e+03],
       [ 5.33650e+03],
       [ 4.86750e+03],
       [ 1.09850e+03],
       [ 4.14050e+03],
       [ 9.34250e+02],
       [ 1.68425e+03],
       [ 9.37000e+02],
       [ 5.47750e+02],
       [ 9.30500e+02],
       [ 3.47750e+03],
       [ 2.22800e+03],
       [ 1.97950e+03],
       [ 2.18400e+03],
       [ 3.80875e+03],
       [ 5.37300e+03],
       [ 1.22025e+03],
       [-8.61500e+02],
       [ 2.55775e+03],
       [ 2.56375e+03],
       [ 5.03425e+03],
       [ 4.20775e+03],
       [ 6.30750e+02],
       [ 3.02750e+02],
       [ 1.03350e+03],
       [ 1.53650e+03],
       [ 1.45200e+03],
       [ 2.63175e+03],
       [ 2.90650e+03],
       [ 1.39675e+03],
       [ 6.18750e+02],
       [ 4.81750e+03],
       [ 2.93425e+03],
       [ 1.06400e+03],
       [ 3.66100e+03],
       [ 2.41250e+02],
       [ 3.44675e+03],
       [ 1.88300e+03],
       [ 3.14775e+03],
       [ 2.58975e+03],
       [ 7.97750e+02],
       [ 6.26750e+02],
       [ 5.48725e+03],
       [ 2.34225e+03],
       [ 2.47425e+03],
       [ 2.26250e+03],
       [ 1.15250e+02],
       [ 2.93825e+03],
       [ 2.45800e+03],
       [ 1.60150e+03],
       [ 7.84000e+02],
       [ 3.79800e+03],
       [ 1.99750e+02],
       [ 2.84025e+03],
       [ 2.48700e+03],
       [-4.35250e+02],
       [ 4.87100e+03],
       [ 2.57625e+03],
       [ 2.71050e+03],
       [ 2.96450e+03],
       [ 2.10500e+03],
       [ 2.60450e+03],
       [ 2.01000e+03],
       [ 2.05050e+03],
       [ 3.35400e+03],
       [ 2.11675e+03],
       [ 2.79625e+03],
       [ 2.89000e+03],
       [ 2.27475e+03],
       [ 1.87300e+03],
       [ 3.08525e+03],
       [ 2.46650e+03],
       [ 2.63425e+03],
       [ 1.70550e+03],
       [ 2.05050e+03],
       [ 2.95850e+03],
       [ 2.86800e+03],
       [ 1.82900e+03],
       [ 4.25075e+03],
       [ 3.89750e+03],
       [ 1.83525e+03],
       [ 3.17900e+03],
       [-7.44250e+02],
       [ 7.18500e+02],
       [ 1.45200e+03],
       [ 1.06250e+03],
       [-5.07250e+02],
       [ 3.02075e+03],
       [ 1.17075e+03],
       [ 8.64000e+02],
       [ 4.29875e+03],
       [ 4.49650e+03],
       [ 3.01200e+03],
       [ 4.95925e+03],
       [ 2.93525e+03],
       [ 4.25000e+00],
       [ 2.33275e+03],
       [ 1.74800e+03],
       [ 7.94750e+02],
       [ 5.63000e+02],
       [ 1.51125e+03],
       [ 3.41450e+03],
       [-9.90500e+02],
       [ 9.90250e+02],
       [ 1.51250e+03],
       [ 2.56025e+03],
       [ 1.32775e+03],
       [ 9.59500e+02],
       [-1.14925e+03],
       [ 4.09325e+03],
       [ 9.33500e+02],
       [ 1.73400e+03],
       [ 2.41625e+03],
       [ 3.51500e+02],
       [ 1.48350e+03],
       [ 3.24325e+03],
       [ 1.09325e+03],
       [ 4.76300e+03],
       [ 2.38275e+03],
       [ 3.82750e+03],
       [ 3.77325e+03],
       [ 2.63600e+03],
       [ 1.55575e+03],
       [ 4.37175e+03],
       [ 2.18950e+03],
       [ 6.20250e+02],
       [ 1.07475e+03],
       [ 5.69500e+02],
       [ 4.25200e+03],
       [ 2.28350e+03],
       [ 2.81975e+03],
       [ 1.87950e+03],
       [ 8.40000e+02],
       [ 6.57500e+02],
       [ 3.02650e+03],
       [ 1.46525e+03],
       [ 4.01475e+03],
       [ 2.39050e+03],
       [ 4.76225e+03],
       [ 3.27750e+03],
       [ 3.69800e+03],
       [ 2.11175e+03],
       [ 1.15750e+03],
       [ 1.88125e+03],
       [-9.03500e+02],
       [ 3.94250e+03],
       [ 4.27050e+03],
       [ 4.93000e+02],
       [ 1.14850e+03],
       [ 2.58875e+03],
       [ 2.14625e+03],
       [ 2.06875e+03],
       [ 2.75325e+03],
       [ 3.77125e+03],
       [ 8.88250e+02],
       [ 4.73600e+03],
       [ 2.90300e+03],
       [ 5.41550e+03],
       [ 4.97250e+02],
       [ 2.55800e+03],
       [ 1.13250e+03],
       [ 2.67375e+03],
       [ 4.94125e+03],
       [ 1.98500e+03],
       [ 3.84525e+03],
       [ 1.27100e+03],
       [ 3.30550e+03],
       [ 4.55725e+03],
       [ 1.62950e+03],
       [ 6.01125e+03],
       [ 5.07675e+03],
       [ 1.20325e+03],
       [ 2.67525e+03],
       [ 2.84350e+03],
       [ 2.03150e+03],
       [ 1.47050e+03],
       [ 3.85825e+03],
       [ 1.94300e+03],
       [ 3.71200e+03],
       [ 1.46225e+03],
       [ 1.94775e+03],
       [ 1.15650e+03],
       [ 2.93550e+03],
       [ 1.22125e+03],
       [ 2.19050e+03],
       [ 2.20450e+03],
       [ 2.48000e+02],
       [ 2.23200e+03],
       [ 2.64300e+03],
       [ 1.56475e+03],
       [ 5.72375e+03],
       [ 5.17350e+03],
       [ 3.12025e+03],
       [ 5.06000e+03],
       [ 1.44025e+03],
       [ 2.01075e+03],
       [ 4.72250e+02],
       [ 1.17125e+03],
       [ 5.93500e+02],
       [ 2.90000e+03],
       [ 4.37850e+03],
       [ 1.51475e+03],
       [ 4.97450e+03],
       [ 1.98775e+03],
       [ 2.97450e+03],
       [ 1.58175e+03],
       [ 2.19525e+03],
       [ 1.90875e+03],
       [ 2.73525e+03],
       [ 3.33400e+03],
       [ 1.77925e+03],
       [ 1.53625e+03],
       [ 1.98175e+03],
       [ 1.84750e+03],
       [ 3.46125e+03],
       [ 1.28150e+03],
       [ 4.49825e+03],
       [ 2.31775e+03],
       [ 3.05750e+02],
       [ 6.50250e+02],
       [ 1.38175e+03],
       [ 2.68400e+03],
       [ 3.61250e+02],
       [ 3.34475e+03],
       [ 2.95325e+03],
       [ 1.95100e+03],
       [-6.27500e+01],
       [ 5.73250e+02],
       [ 2.60550e+03],
       [-1.14250e+02],
       [ 1.45025e+03],
       [-1.94700e+03],
       [ 1.20625e+03],
       [-1.21275e+03],
       [ 1.69525e+03],
       [ 3.74800e+03],
       [ 5.45125e+03],
       [ 5.07800e+03],
       [ 1.77350e+03],
       [ 1.47550e+03],
       [ 3.32250e+02],
       [ 4.23000e+03],
       [ 2.18800e+03],
       [ 5.61975e+03],
       [ 3.36975e+03],
       [ 1.04025e+03],
       [ 2.06825e+03],
       [ 2.06500e+03],
       [ 1.74350e+03],
       [ 1.85750e+03],
       [ 1.46175e+03],
       [ 9.68000e+02],
       [ 1.12550e+03],
       [ 2.72900e+03],
       [ 2.01725e+03],
       [ 3.39950e+03],
       [ 3.70650e+03],
       [ 2.60475e+03],
       [ 7.14000e+02],
       [ 3.41950e+03],
       [ 1.05825e+03],
       [-9.69000e+02],
       [ 2.33425e+03],
       [ 2.30625e+03],
       [ 1.77425e+03],
       [ 8.93000e+02],
       [ 3.78650e+03],
       [ 1.62550e+03],
       [ 1.32625e+03],
       [ 6.88500e+02],
       [ 3.42375e+03],
       [ 3.08775e+03],
       [ 3.13850e+03],
       [ 4.53850e+03],
       [ 2.45025e+03],
       [ 1.47800e+03],
       [ 4.55000e+01],
       [ 2.27350e+03],
       [ 1.70925e+03],
       [ 6.99000e+02],
       [ 3.07250e+02],
       [ 1.64100e+03],
       [ 8.18000e+02],
       [ 4.21250e+02],
       [ 1.46450e+03],
       [ 1.30200e+03],
       [ 1.47100e+03],
       [ 3.65325e+03],
       [-8.99500e+02],
       [ 1.72275e+03],
       [ 1.32175e+03],
       [ 2.33750e+03],
       [ 1.30225e+03],
       [ 4.20325e+03],
       [ 1.46125e+03],
       [ 3.88150e+03],
       [ 3.78100e+03],
       [ 3.21225e+03],
       [ 1.62900e+03],
       [ 9.62500e+02],
       [ 4.20125e+03],
       [ 2.45675e+03],
       [ 2.26225e+03],
       [ 2.23575e+03],
       [ 5.07600e+03],
       [ 2.33650e+03],
       [ 9.76250e+02],
       [ 2.23075e+03],
       [ 1.34700e+03],
       [ 1.31400e+03],
       [ 1.27650e+03],
       [ 4.00925e+03],
       [ 2.78675e+03],
       [ 3.85725e+03],
       [ 5.88650e+03],
       [ 2.13475e+03],
       [ 1.90200e+03],
       [ 7.34750e+02],
       [ 2.87525e+03],
       [ 2.98250e+03],
       [ 3.28150e+03],
       [ 5.21900e+03],
       [ 1.26925e+03],
       [ 4.71775e+03],
       [ 7.96250e+02],
       [ 1.57725e+03],
       [ 1.48575e+03],
       [ 1.07950e+03],
       [ 1.34250e+02],
       [ 8.88000e+02],
       [ 1.75250e+03],
       [ 2.26500e+03],
       [ 2.75000e+03],
       [ 1.55375e+03],
       [ 4.01875e+03],
       [ 1.88100e+03],
       [ 3.99550e+03],
       [ 2.07575e+03],
       [ 2.63225e+03],
       [ 1.54275e+03],
       [ 9.82000e+02],
       [ 3.38875e+03],
       [ 3.82950e+03],
       [ 4.27325e+03],
       [ 6.32500e+02],
       [ 1.27825e+03],
       [ 2.79700e+03],
       [ 2.37550e+03],
       [ 4.74200e+03],
       [ 2.12275e+03],
       [-1.92250e+02],
       [ 3.75000e+00],
       [ 3.85725e+03],
       [ 2.95450e+03],
       [ 4.39200e+03],
       [ 2.83300e+03],
       [ 1.95975e+03],
       [ 2.51750e+02],
       [ 6.60750e+02],
       [ 1.23925e+03],
       [ 2.55600e+03],
       [ 2.30125e+03],
       [ 2.68350e+03],
       [ 1.06575e+03],
       [ 2.64200e+03],
       [ 2.72975e+03],
       [ 7.67750e+02],
       [ 3.49375e+03],
       [ 4.91450e+03],
       [ 2.42300e+03],
       [ 1.84375e+03],
       [ 3.05950e+03],
       [ 4.04975e+03],
       [ 3.20500e+03],
       [ 2.07775e+03],
       [ 5.09650e+03],
       [ 8.29250e+02],
       [ 1.67050e+03],
       [ 8.88750e+02],
       [ 1.06900e+03],
       [ 1.93650e+03],
       [ 1.73075e+03],
       [ 7.66750e+02],
       [ 1.78975e+03],
       [ 1.66925e+03],
       [ 4.37750e+02],
       [ 1.82350e+03],
       [ 2.46275e+03],
       [ 1.17250e+03],
       [ 7.91500e+02],
       [ 1.41700e+03],
       [-9.51750e+02],
       [-3.38750e+02],
       [ 1.52475e+03],
       [ 2.13325e+03],
       [ 4.56075e+03],
       [-3.61500e+02],
       [-5.68750e+02],
       [ 1.50875e+03],
       [ 2.76950e+03],
       [ 4.75425e+03],
       [ 2.60675e+03],
       [ 3.66675e+03],
       [ 3.43150e+03],
       [ 3.03675e+03],
       [ 1.59075e+03],
       [ 1.77800e+03],
       [ 2.40625e+03],
       [ 9.57250e+02],
       [ 8.23500e+02],
       [ 8.80750e+02],
       [ 2.40075e+03],
       [ 1.40950e+03],
       [ 2.23600e+03],
       [ 2.11250e+03],
       [ 3.51100e+03],
       [ 3.62650e+03],
       [ 2.24425e+03],
       [ 2.98625e+03],
       [ 1.19625e+03],
       [ 2.57400e+03],
       [ 2.94350e+03],
       [ 2.31750e+03],
       [ 9.65500e+02],
       [-1.02700e+03],
       [ 2.67575e+03],
       [ 2.34725e+03],
       [ 5.02100e+03],
       [ 9.22000e+02],
       [ 1.89150e+03],
       [ 2.20125e+03],
       [ 1.87700e+03],
       [ 1.72325e+03],
       [ 2.06075e+03],
       [-9.98750e+02],
       [ 1.73125e+03],
       [ 3.31675e+03],
       [ 3.19250e+02],
       [ 9.01500e+02],
       [ 4.01175e+03],
       [ 1.26325e+03],
       [ 8.80000e+01],
       [ 1.36025e+03],
       [ 4.34500e+03],
       [ 2.25900e+03],
       [ 4.28175e+03],
       [ 4.90250e+02],
       [ 2.97275e+03],
       [ 1.72575e+03],
       [ 1.86800e+03],
       [ 1.51400e+03],
       [ 1.67850e+03],
       [ 2.35575e+03],
       [ 3.37100e+03],
       [ 1.09825e+03],
       [ 1.94925e+03],
       [ 1.96150e+03],
       [ 3.14825e+03],
       [ 3.21000e+02],
       [ 1.35775e+03],
       [ 8.77500e+02],
       [ 9.85000e+02],
       [ 2.28225e+03],
       [ 1.78725e+03],
       [ 3.77975e+03],
       [ 6.60250e+02],
       [ 1.33250e+03],
       [ 2.31325e+03],
       [ 1.81850e+03],
       [ 3.30550e+03],
       [ 2.13550e+03],
       [ 1.40450e+03],
       [ 2.40500e+02],
       [ 9.66000e+02],
       [ 1.95975e+03],
       [ 1.71350e+03],
       [ 2.03625e+03],
       [ 5.33275e+03],
       [-1.16050e+03],
       [ 5.18375e+03],
       [ 4.01350e+03],
       [ 9.48000e+02],
       [ 1.00900e+03],
       [ 3.31075e+03],
       [ 1.52500e+03],
       [ 3.57525e+03],
       [ 1.92200e+03],
       [ 2.25175e+03],
       [ 3.91875e+03],
       [ 2.51125e+03],
       [ 1.94450e+03],
       [ 2.08925e+03],
       [ 2.42750e+03],
       [ 1.50750e+03],
       [ 1.65650e+03],
       [ 2.43550e+03],
       [ 4.09725e+03],
       [ 4.05450e+03],
       [ 2.91425e+03],
       [ 1.59475e+03],
       [ 2.06800e+03],
       [ 2.97425e+03],
       [ 4.70875e+03],
       [ 4.08050e+03],
       [ 2.01350e+03],
       [ 1.62325e+03],
       [ 1.10625e+03],
       [ 2.30200e+03],
       [ 1.23475e+03],
       [ 3.39475e+03],
       [ 3.75700e+03],
       [ 2.90075e+03],
       [ 1.10275e+03],
       [ 1.76225e+03],
       [ 1.40125e+03]])

In [19]:
# For checking the performance we use R-Squared method on test data
lreg.score(x_test,true_p)

0.40232441433688915

In [20]:
# For checking the performance we use R-Squared method on train data
lreg.score(x_train,y_train)

0.6497744224112083

We can see that there is a huge difference between train dataset & test dataset so it might be either the model overfitted training dataset or test dataset is not a represntative of train dataseta. It reqiures more investigation.

In [21]:
# Evaluation of model - RMSE i.e (Target Actual- Target Predict). There is no use of independent variable
rmse_test = np.sqrt(np.mean(np.power((np.array(true_p)-np.array(pred)),2)))
rmse_test

2151.4879304275755

In [22]:
rmse_train = np.sqrt(np.mean(np.power((np.array(y_train)-np.array(lreg.predict(x_train))),2)))
rmse_train

1013.0028358134837